# Using Pandas

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 200)
## to make it possible to display multiple output inside one cell 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

<b>load the data from the vehicles.csv file into pandas data frame

In [2]:
## Your Code here
cars_df = pd.read_csv("vehicles.csv")
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In [3]:
cars_df.head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

First exploration of the dataset:

- How many observations does it have?
- Look at all the columns: do you understand what they mean?
- Look at the raw data: do you see anything weird?
- Look at the data types: are they the expected ones for the information the column contains?

In [4]:
#35952 rows (Ã— 15 columns)
    #Engine Displacement = Hubraum
    #drivetrain = Antriebsstrang
    #MPG = miles per gallon

In [5]:
cars_df.info() #35952 observations

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  int64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(3), int64(6), object(6)
memory usage: 4.1+ MB

In [7]:
# datatype string doesn't exist in pandas
# datatyp object can mean it is a string or more than one datatype in pandas

### Cleaning and wrangling data

- Some car brand names refer to the same brand. Replace all brand names that contain the word "Dutton" for simply "Dutton". If you find similar examples, clean their names too. Use `loc` with boolean indexing.

- Convert CO2 Emissions from Grams/Mile to Grams/Km

- Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use `pandas.Series.str.startswith` and .

- convert MPG columns to km_per_liter

Note:
<br>Converting Grams/Mile to Grams/Km

1 Mile = 1.60934 Km

Converting Gallons to Liters

1 Gallon = 3.78541 Liters

In [8]:
cars_df["Make"]=="Dutton"
sum(cars_df["Make"]=="Dutton") #3x True, 3 values Dutton

0        False
1        False
2        False
3        False
4        False
         ...
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Make, Length: 35952, dtype: bool

0

In [9]:
cars_df.iloc[11012,0]

'E. P. Dutton, Inc.'

In [10]:
cars_df = cars_df.apply(lambda x: "Dutton" if "Dutton" in x else x)

In [11]:
cars_df.iloc[11012,0]

'E. P. Dutton, Inc.'

In [12]:
cars_df.loc[cars_df["Make"].str.contains("Dutton"), "Make"]= "Dutton"

In [13]:
cars_df.iloc[11012,0]

'Dutton'

In [14]:
cars_df["Make"]=="Dutton"
sum(cars_df["Make"]=="Dutton") #3x True, 3 values Dutton

0        False
1        False
2        False
3        False
4        False
         ...
35947    False
35948    False
35949    False
35950    False
35951    False
Name: Make, Length: 35952, dtype: bool

3

In [15]:
print(str.contains.__doc__)

AttributeError: type object 'str' has no attribute 'contains'

In [16]:
#Convert CO2 Emissions from Grams/Mile to Grams/Km
cars_df["CO2 Emission Grams/Mile"]=cars_df["CO2 Emission Grams/Mile"].apply(lambda x: x *1.60934)

In [17]:
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,841.306152,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,893.887786,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,893.887786,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35948,smart,fortwo coupe,2014,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,391.069620,1100
35949,smart,fortwo coupe,2015,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35950,smart,fortwo coupe,2016,0.9,3,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,395.897640,1100
35951,smart,fortwo coupe,2016,0.9,3,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,410.381700,1150

In [18]:
#rename CO2 Emissions from Grams/Mile to Grams/Km
cars_df = cars_df.rename(columns={"CO2 Emission Grams/Mile":"CO2 Emission Grams/Km"})
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,841.306152,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,893.887786,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,893.887786,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35948,smart,fortwo coupe,2014,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,391.069620,1100
35949,smart,fortwo coupe,2015,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35950,smart,fortwo coupe,2016,0.9,3,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,395.897640,1100
35951,smart,fortwo coupe,2016,0.9,3,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,410.381700,1150

In [19]:
#Create a binary column that solely indicates if the transmission of a car is automatic or manual. Use pandas.Series.str.startswith and .
binary_column = cars_df["Transmission"].str.startswith("A")
binary_column

0         True
1         True
2         True
3         True
4         True
         ...
35947     True
35948     True
35949     True
35950     True
35951    False
Name: Transmission, Length: 35952, dtype: bool

In [20]:
cars_df = cars_df.replace("MPG", "km_per_liter", regex = True)

In [21]:
cars_df #doesnt work

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Km,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,841.306152,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,893.887786,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,893.887786,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35948,smart,fortwo coupe,2014,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,391.069620,1100
35949,smart,fortwo coupe,2015,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35950,smart,fortwo coupe,2016,0.9,3,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,395.897640,1100
35951,smart,fortwo coupe,2016,0.9,3,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,410.381700,1150

In [22]:
#convert MPG columns to km_per_liter
cars_df = cars_df.rename(columns={"City MPG":"City km/l","Highway MPG":"Highway km/l","Combined MPG" :"Combined km/l" })

In [23]:
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City km/l,Highway km/l,Combined km/l,CO2 Emission Grams/Km,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,841.306152,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,893.887786,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,893.887786,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35948,smart,fortwo coupe,2014,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,391.069620,1100
35949,smart,fortwo coupe,2015,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35950,smart,fortwo coupe,2016,0.9,3,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,395.897640,1100
35951,smart,fortwo coupe,2016,0.9,3,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,410.381700,1150

In [27]:
cars_df[["City km/l","Highway km/l","Combined km/l"]].apply(lambda x: x * 1.60934 / 3.78541)

SyntaxError: cannot assign to function call (928293313.py, line 1)

In [25]:
cars_df

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City km/l,Highway km/l,Combined km/l,CO2 Emission Grams/Km,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,841.306152,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,893.887786,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,1100.169583,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,893.887786,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35948,smart,fortwo coupe,2014,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,391.069620,1100
35949,smart,fortwo coupe,2015,1.0,3,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,392.678960,1100
35950,smart,fortwo coupe,2016,0.9,3,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,395.897640,1100
35951,smart,fortwo coupe,2016,0.9,3,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,410.381700,1150

### Gathering insights:

- How many car makers are there? How many models? Which car maker has the most cars in the dataset?

- When were these cars made? How big is the engine of these cars?

- What's the frequency of different transmissions, drivetrains and fuel types?

- What's the car that consumes the least/most fuel?

In [28]:
#How many car makers are there? How many models? 
cars_df.nunique()

Make                      125
Model                    3608
Year                       34
Engine Displacement        65
Cylinders                   9
Transmission               45
Drivetrain                  8
Vehicle Class              34
Fuel Type                  13
Fuel Barrels/Year         123
City km/l                  48
Highway km/l               49
Combined km/l              46
CO2 Emission Grams/Km     575
Fuel Cost/Year             55
dtype: int64

In [33]:
#Which car maker has the most cars in the dataset?
cars_df["Make"].describe()

count         35952
unique          125
top       Chevrolet
freq           3643
Name: Make, dtype: object

In [37]:
#When were these cars made?
cars_df["Year"].unique()

array([1984, 1985, 1987, 1997, 1998, 1999, 1995, 1996, 2001, 2002, 2003,
       2000, 2004, 2013, 2014, 2015, 2016, 2017, 1986, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012], dtype=int64)

In [38]:
#How big is the engine of these cars?
cars_df["Engine Displacement"].unique()

array([2.5, 4.2, 3.8, 2.2, 3. , 2.3, 3.2, 3.5, 2. , 2.4, 1.5, 1.6, 1.8,
       1.7, 2.7, 3.7, 4.7, 5.9, 5.3, 6. , 4.3, 2.8, 2.1, 1.4, 3.1, 4. ,
       6.3, 3.6, 5.2, 4.9, 5. , 1.9, 3.4, 4.4, 4.8, 5.4, 5.6, 4.6, 0.6,
       6.7, 6.8, 3.9, 8. , 3.3, 5.7, 4.1, 4.5, 6.2, 6.5, 7.4, 7. , 2.9,
       1. , 1.3, 1.2, 6.4, 6.1, 2.6, 8.3, 8.4, 5.5, 5.8, 1.1, 6.6, 0.9])

In [39]:
#What's the frequency of different transmissions, drivetrains and fuel types?
#top is the most common value. The freq is the most common valueâ€™s frequency. 
cars_df["Transmission"].describe()

count               35952
unique                 45
top       Automatic 4-spd
freq                10585
Name: Transmission, dtype: object

In [40]:
cars_df["Drivetrain"].describe()

count                 35952
unique                    8
top       Front-Wheel Drive
freq                  13044
Name: Drivetrain, dtype: object

In [42]:
cars_df["Fuel Type"].describe()

count       35952
unique         13
top       Regular
freq        23587
Name: Fuel Type, dtype: object

In [43]:
#What's the car that consumes the least/most fuel?
cars_df["Fuel Barrels/Year"].describe()

count    35952.000000
mean        17.609056
std          4.467283
min          0.060000
25%         14.699423
50%         17.347895
75%         20.600625
max         47.087143
Name: Fuel Barrels/Year, dtype: float64

<b> (Optional)

What brand has the worse CO2 Emissions on average?

Hint: use the function `sort_values()`

In [28]:
## your Code here

Do cars with automatic transmission consume more fuel than cars with manual transmission on average?

In [20]:
## Your Code is here